### ISSUE TITLE
ReactDefaults ?

### ISSUE THREAD

**Issue by chandu0101** [japgolly/scalacss#15]
Current Defaults trait full fills general needs , what about ReactDefaults which contains react specific helpers .

```scala
trait ReactDefaults extends Defaults {

  implicit override def register: Register = ???

}
```
its good to have register which will prefix class names with react component name , at this moment i am not sure weather its possible or not!

**Comment by japgolly** [comment]
I considered making a ReactDefaults but realised there was nothing in the defaults that needed changing.

Prefixing class names with the React component name is... I don't see how that's possible. In order to make that possible we would need to address the larger problem of best practices for styled generic components. How to solve that is unclear at this point. It would be best for us all to explore our own ideas in our different codebases and share experiences in, say, 2 months or so.

I'll close this for now; we can reopen in future.
