### ISSUE TITLE
Update Docs for 0.6

### ISSUE THREAD

**Issue by swoogles** [japgolly/scalacss#193]
Currently they are still written for 0.5.3, which has no 2.13 release. The basic getting started examples no longer work.

**Comment by japgolly** [comment]
Thanks for letting me know. The problem wasn't that the docs weren't updated for 0.6.0, it turns out I'd just forgotten to manually (urgh) add a link to the 0.6.x changelogs which made it look like they hadn't been updated seen 0.5.3.

Also about the getting started examples not working, I just tried them both and they worked for me. What was the problem you were seeing?

**Comment by swoogles** [comment]
Actually, investigating further, sbt will build things just fine.

It's Intellij that's utterly failing to recognize the scalacss bits, which is surprising, since it's worked out of the box with some older projects.
Link to the build.sbt file here: https://github.com/WinterTechForum/cb-bus/blob/master/build.sbt
All the other libs in this ScalaJS project are working smoothly in Intellij.

I also completely understand if this out of scope of your project and you don't want to go down that rabbit hole.

**Comment by swoogles** [comment]
![ScalaCSSOutdatedVersion](https://user-images.githubusercontent.com/2054940/74786708-9c44ff80-526a-11ea-892f-ad1639f6aa1a.PNG)

Still seeing 0.5.3 here

**Comment by japgolly** [comment]
Sorry @swoogles I actually thought I closed this off ages ago. Oh well, updated now :)
