### ISSUE TITLE
Support @font-face in standalone stylesheet

### ISSUE THREAD

**Issue by mysticfall** [japgolly/scalacss#80]
Currently, the `@font-face` macro enforces its `font-family` name to be unique, by automatically prefixing it with the enclosing class name, but in certain scenarios, it is required to have a fixed `font-family` name.

For instance, if we have some existing markups which cannot be modified and contain inline CSS with 'font-family' attributes(i.e. `<p style="font-family: Open Sans">...</p>`), we need to declare `@font-face` with the exact name to be able to display the content properly.

Furthermore, if the loaded font supports multiple styles, it is needed to declare matching `@font-face` rules with the same `font-family` name, both of which cannot be done with the current implementation.

As an example, below is the automatically generated CSS for _Open Sans_ on Google Fonts:
- https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600

For now, it seems to be impossible to build a similar service using _Scalacss_, as it does not allow using a specific `font-family` name for `@font-face` rules, or using it multiple times in a stylesheet.

It would be better if we can extend the standalone stylesheet to cover such use cases.

**Comment by japgolly** [comment]
@Starzu Is there any reason to *require* a `font-family`? We mangle it to ensure it's unique but we never reference it via its name anyway, we reference it using the `FontFace` reference. It might be a better idea to change it so that:
* The constructor doesn't require a font-family name.
* If a font-family name is manually provided, we don't modify it.
* If a font-family name isn't provided, we generate a unique one.

**Comment by Starzu** [comment]
@japgolly it sounds reasonable.

**Comment by japgolly** [comment]
Fixed in v0.5.2-RC1
